---
- name: Install galaxy
  hosts: master
  gather_facts: "yes"

  tasks:
    # Galaxy
    - name: Galaxy
      include_role:
        name: roles/galaxy
      vars:
        hostname: "{{galaxy_hostname}}"
        galaxy_api_key: "{{ lookup('password', 'galaxy-api-key-generated length=25 chars=ascii_letters') }}"
        galaxy_pvc: "{{pvc_name}}"
        postgres_pvc: "{{pvc_name}}"
        nologging: "{{galaxy_nologging}}"
